export const actionTypes = {
    UPDATE_TEXT: 'UPDATE_TEXT',
    UPDATE_SEARCH: 'UPDATE_SEARCH',
    SET_CURRENT_CITY_DETAILS: 'SET_CURRENT_CITY_DETAILS',
    TOGGLE: 'TOGGLE',
    UPDATE_FORECAST: 'UPDATE_FORECAST',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    SET_FAVORITE_CITY_DETAILS: 'SET_FAVORITE_CITY_DETAILS',
    FIRST_TIME_FINISHED: 'FIRST_TIME_FINISHED',
    CLEAR: 'CLEAR',
    REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
    TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE',
    CLOSE_MODAL: 'CLOSE_MODAL',
    OPEN_MODAL: 'OPEN_MODAL',
    UPDATE_FAVORITES: 'UPDATE_FAVORITES',
    FIRST_TIME_FINISHED_FAVORITES: 'FIRST_TIME_FINISHED_FAVORITES',
    LOADING: 'LOADING',
    FINISHED_LOADING: 'FINISHED_LOADING'
};

